CREATE SEQUENCE "MY_SEQ" START WITH 2 BELONGS_TO_TABLE;

CREATE TABLE RECIPE (
    "ID" BIGINT DEFAULT NEXT VALUE FOR "MY_SEQ" NOT NULL NULL_TO_DEFAULT SEQUENCE "MY_SEQ",
    "INGREDIENTS" VARCHAR(255),
    "INSTRUCTIONS" VARCHAR(255),
    "SERVINGS" INTEGER,
    "RECIPE_NAME" VARCHAR(255),
    "IS_VEG" BOOLEAN NOT NULL
);